# application-prod.yml
spring:
  data:
    mongodb:
      # En prod: nunca URI hardcodeada. Variables de entorno inyectadas por Jenkins/Docker (-e), tal como ya haces con tus otros secrets
      uri: ${MONGODB_URI}
      auto-index-creation: false  # en prod los índices se gestionan explícitamente, nunca "mágicamente" en el arranque

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN